### DISCUSSION TITLE
Reverse proxy config like Jellyfin's official documents

### DISCUSSION THREAD

**Discussion by t0ury** [jellyfin/jellyfin-vue#2200] [Questions] [answered]
## How to setup reverse proxy for jellyfin-vue 
Jellyfin has many reverse proxy config tutorial for different proxy server in their [documents](https://jellyfin.org/docs/general/networking/nginx).

Does jellyfin-vue uses the same setup like jellyfin-web when using reverse proxy server like Nginx?
I didn't find any info about reverse proxy config migration in your Wiki.

## How to migrate reverse proxy setup from jellyfin-web
Currently I use nginx to forward requests to Jellyfin with https, Since jellyfin-vue by default using http protocol, I was wondering if should remain the same settings in nginx's configuration file to reverse proxy jellyfin-vue.

**Comment by kimboslice99** [comment]
jellyfin-vue is only a client, you do not need to reverse proxy unless you mount jellyfin-vue as the webclient with `JELLYFIN_WEB_DIR` environment variable.

This should allow you to serve it from nginx while keeping the original client at /web/, havent tested however
```
    location /vue/ {
        alias /path/to/jellyfin-vue/;
    }
```

**Comment by ferferga** [comment, marked as answer]
Do the new docs clarify things further?
https://jellyfin.org/docs/general/clients/jellyfin-vue and https://github.com/jellyfin/jellyfin-vue/wiki/Deployment

Have you been able to solve your doubt?

**Reply by t0ury** [reply]
Yes, it does. It looks like they added more details about jellyfin-vue in the documents. The new documentation provides more clarity, and I was able to resolve my doubt. Thanks!

**Comment by YouveGotMeowxy** [comment]
Hi guys

I'm trying to setup vue and my reverse proxy in swag and have read everything and still having problems. Can anyone help me straighten this all out?

I'll just paste everything I have:

**docker compose:**

```
services:

  jellyfin:
    hostname: 'jellyfin'
    image: 'ghcr.io/linuxserver/jellyfin:latest'
    environment:
      TZ: 'America/Chicago'
      PUID: '1000'
      PGID: '1000'
      JELLYFIN_PublishedServerUrl: 'https://jellyfin.mydomain.com'
      NVIDIA_VISIBLE_DEVICES: 'all'
    runtime: 'nvidia'
    volumes:
      - '/mnt/g/Jellyfin:/config'
      - '/mnt/e/Media/Media Server/Movies:/data/movies'
      - '/mnt/e/Media/Media Server/TV:/data/tvshows'
    labels:
      swag.uptime-kuma.enabled: "true"
      swag.uptime-kuma.monitor.name: "Jellyfin (Bridged)"
      swag.uptime-kuma.monitor.url: "https://jellyfin.mydomain.com"
      swag.uptime-kuma.monitor.description: "[OC] Jellyfin Media Server"
      swag.uptime-kuma.monitor.parent: "HTPC"
      com.ouroboros.enable: 'true'
    networks:
      - 'htpc'
      - 'metrics'
      - 'web'
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8096/health"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5s
    deploy:
      resources:
        limits:
          memory: '8G'
    restart: unless-stopped

  jellyfin-vue:
    hostname: 'jellyfin-vue'
    image: 'ghcr.io/jellyfin/jellyfin-vue:unstable'
    environment:
      DEFAULT_SERVERS: 'https://jellyfin.mydomain.com'
      DISABLE_SERVER_SELECTION: 0
    labels:
      com.ouroboros.enable: 'true'
    networks:
      - 'htpc'
      - 'web'
    restart: unless-stopped
    depends_on:
      - 'jellyfin'

networks:
  htpc:
    external: true
    name: 'htpc'
  metrics:
    external: true
    name: 'metrics'
  web:
    external: true
    name: 'web'
```

**jellyfin.subdomain.conf**

```
server {
    listen 443 ssl;
    listen 443 quic;
    listen [::]:443 ssl;
    listen [::]:443 quic;

    server_name jellyfin.*;

    include /config/nginx/ssl.conf;
    include /config/nginx/global.conf;
    client_max_body_size 20M;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app jellyfin;
        set $upstream_port 8096;
        set $upstream_proto http;
        if ($http_user_agent ~ Web0S) {
            add_header Access-Control-Allow-Origin "luna://com.webos.service.config" always;
        }
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;

        proxy_set_header Range $http_range;
        proxy_set_header If-Range $http_if_range;
        proxy_set_header Accept-Encoding "";
        sub_filter '</head>' '<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/Druidblack/jellyfin-icon-metadata@main/public-icon.css"></head>';
        sub_filter_once on;
    }

    location ~ (/jellyfin)?/socket {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app jellyfin;
        set $upstream_port 8096;
        set $upstream_proto http;
        if ($http_user_agent ~ Web0S) {
            add_header Access-Control-Allow-Origin "luna://com.webos.service.config" always;
        }
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
    location /metrics {
        allow 10.0.0.0/8;
        allow 127.0.0.0/8;
        allow 172.16.0.0/12;
        allow 192.168.0.0/16;
        deny all;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app jellyfin;
        set $upstream_port 8096;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

**jellyfin-vue.subdomain.conf**

```

server {
    listen 443 ssl;
    listen 443 quic;
    listen [::]:443 ssl;
    listen [::]:443 quic;

    server_name jellyfin-vue.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;
    include /config/nginx/authelia-server.conf;

    location / {
        include /config/nginx/authelia-location.conf;

        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app jellyfin-vue;
        set $upstream_port 80;
        set $upstream_proto http;
        if ($http_user_agent ~ Web0S) {
            add_header Access-Control-Allow-Origin "luna://com.webos.service.config" always;
        }
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
```

I have no orange cloud set for the subdomain in CloudFlare.
In JF Dashboard -> Networking I have no base URL set, and I have Firewall and Proxy Settings -> Published Server URIs to:

    all=https://jellyfin.mydomain.com

**Remote Access Settings:**

<img width="830" height="617" alt="image" src="https://github.com/user-attachments/assets/045199f6-7fb0-4370-ad19-7e4d98486147" />

Then when loading this **Jellyfin** page (for example), dev inspector shows these errors;

https://jellyfin.mydomain.com/web/index.html#/dashboard/networking

<img width="474" height="245" alt="image" src="https://github.com/user-attachments/assets/429d5e7d-e42b-4462-b28d-7246869012d5" />

and the dev console when loading a VUE page, shows (also note aside from all the 404's, the 2 connection refused at the end):

<img width="470" height="1110" alt="image" src="https://github.com/user-attachments/assets/b711257d-ca0c-4af3-be69-a3d73f524a97" />

I've fought with ChatGPT, a hundred different config trial and errors, and so forth and I'm at my wits end. I'm just trying to get JF Vue working! lol

Anyone know what's wrong here?
