### DISCUSSION TITLE
Compose file?

### DISCUSSION THREAD

**Discussion by BoBBer446** [jellyfin/jellyfin-vue#2446] [Questions] [answered]
Hey there, i was using this one as a test:
```yml
services:
  jellyfin:
    image: ghcr.io/jellyfin/jellyfin-vue:unstable
    container_name: jellyfin-vue
    hostname: jellyfin-vue

    network_mode: "bridge"
    ports:
      - 8097:8096
      - 7360:7359/udp # Server finden
      - 8921:8920 # optional
      - 1901:1900/udp # Optional
    volumes:
      - /home/docker-projects/jellyfin_test/volumes/config:/config
      - /home/docker-projects/jellyfin_test/volumes/cache:/cache
      - /home/nas/Filme:/media/Filme
      - /home/nas/Serien:/media/Serien
      - /home/nas/Videos:/media/Videos
      - /dev/shm:/data/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      - TZ=Europe/Berlin
    restart: always
```
Can anybody see my fault ?
