### ISSUE TITLE
JV says it requires >10.7.0 due to missing CORS headers

### ISSUE THREAD

**Issue by Tragyn** [jellyfin/jellyfin-vue#1843]
### Description of the bug

Installed Jellyfin Vue from here: https://hub.docker.com/r/jellyfin/jellyfin-vue

When adding my Jellyfin server, the UI erorrs and says it requires the version of Jellyfin to be greater than 10.7.0. Current Jellyfin version is 10.8.8.

### Steps to reproduce

Install Jellyfin 10.8.8
Install Jellyfin Vue
Attempt to add Jellyfin server to Jellyfin Vue

### Expected behavior

Server is added to JF Vue

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

10.8.8

**Comment by jathek** [comment]
Did you find a way to fix this? I'm seeing the same issue.

**Comment by ferferga** [comment]
@jathek What's the error in the browser's console?

Make sure your server is on HTTPS if using the hosted instance.

**Comment by jathek** [comment]
> @jathek What's the error in the browser's console?
> 
> Make sure your server is on HTTPS if using the hosted instance.

It was already on https. I was getting cors errors in the console when I couldn't log in. I added the below to my headers middleware in traefik and it solved that.
I was still getting a warning on the jellyfin-vue login page that the server version required was too low, but after adding the `DEFAULT_SERVERS` to my container that problem seems to have been bypassed.

```yaml
        accessControlAllowCredentials: true
        accessControlAllowHeaders: [ "Authorization","Content-Type" ] # "Accept","Origin"
        accessControlAllowMethods: [ "GET","HEAD","OPTIONS" ] # "POST","PUT"
        accessControlAllowOriginList: "*"
        accessControlMaxAge: 100
```
