### ISSUE TITLE
"Expected allowServerSelection to be boolean" when loading page

### ISSUE THREAD

**Issue by gpregger** [jellyfin/jellyfin-vue#2234]
### Description of the bug

Running as a container on TrueNAS SCALE, out of the box, the Jellyfin Vue page hangs at the logo. JavaScript console says

```
Uncaught Error: Expected allowServerSelection to be boolean
    at vX (main-_u_gSW0o.js:58:38342)
    at gu (main-_u_gSW0o.js:58:38653)
    at async main-_u_gSW0o.js:58:40192
```

Turns out `type of t.allowServerSelection` in this context is 'string' not boolean.

My config.json:

```
{
  "defaultServerURLs": [
    "xxxxxxxx",
    "xxxxxxxx"
  ],
  "allowServerSelection": "false",
  "routerMode": "history"
}
```

Simply removing the quotes in around "false" at "allowServerSelection" fixes the issue (or at least works around it until the container is restarted of course)

### Steps to reproduce

I imagine this will occur naturally when running the JFV container, commit 45dbcbb

### Expected behavior

Page should load

### Platform

Linux

### Browser

Chrome

### Jellyfin server version

10.9

**Comment by Linguiniotta** [comment]
I am also experiencing the same issue but with docker-compose.

Here is my yaml:

```
jellyvue:
    image: jellyfin/jellyfin-vue:unstable
    container_name: jellyvue
    restart: always
    stdin_open: true
    ports:
      - ${JELLYFIN_VUE_PORT:8080}:80
    networks:
      - net_external
    environment:
      - DEFAULT_SERVERS=${JELLYFIN_DEFAULT_SERVERS}
      - ALLOW_SERVER_SELECTION=${ALLOW_SERVER_SELECTION:-1}
      - HISTORY_ROUTER_MODE=${HISTORY_ROUTER_MODE:-1}
    env_file:
      - ${ENV_FILE:-.env}
```

Not sure if relevant, but here are also logs from docker compose:

<details>
    <summary>docker compose logs jellyvue</summary>
<code>
jellyvue  | ==== Starting Jellyfin Vue setup ====
jellyvue  | 
jellyvue  | Writing data to /usr/share/nginx/html/config.json...
jellyvue  | DEFAULT_SERVERS value: https://jellyfin.user.com,https://jellyfin.internal.user.com
jellyvue  | ALLOW_SERVER_SELECTION value: true
jellyvue  | ROUTER_MODE value: history
jellyvue  | 
jellyvue  | ====      Setup finished!        ====
jellyvue  | 
jellyvue  | 
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: using the "epoll" event method
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: nginx/1.24.0
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: built by gcc 12.2.1 20220924 (Alpine 12.2.1_git20220924-r4) 
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: OS: Linux 6.7.5-arch1-1
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1073741816:1073741816
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker processes
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 9
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 10
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 11
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 12
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 13
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 14
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 15
jellyvue  | 2024/02/24 02:06:41 [notice] 1#1: start worker process 16
</code>
</details>
