### ISSUE TITLE
Research/fix Docker install #Help

### ISSUE THREAD

**Issue by ldexterldesign** [jellyfin/jellyfin-vue#256]
Hi!

Thanks for software

I'm using [this] Docker image but unable to successfully run it

docker-compose.yaml:
```yaml
version: "3"
services:

  jellyfin:
    container_name: jellyfin_beta
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    image: jellyfin/jellyfin-vue:unstable
    ports:
      - 8097:8097
    restart: unless-stopped
    volumes:
      # - /Volumes/synology/gtd/home/reference:/-data/jellyfin/synology
      - ~/Downloads/-data/-config/jellyfin:/config
      - ~/Downloads/-data:/-data/jellyfin/apple
```

log:
```sh
Last login: Thu Nov  5 20:13:00 on ttys000
ldexterldesign@apple ~ % cd /Volumes/Secomba/ldexterldesign/Boxcryptor/Dropbox/gtd/home/calendar/Sanitise\ device\ -\ apple/docker/jellyfin\ -\ beta
ldexterldesign@apple jellyfin - beta % docker-compose up
jellyfin_beta is up-to-date
Attaching to jellyfin_beta
jellyfin_beta | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
jellyfin_beta | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
jellyfin_beta | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
jellyfin_beta | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
jellyfin_beta | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packages version
jellyfin_beta | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
jellyfin_beta | /docker-entrypoint.sh: Configuration complete; ready for start up
jellyfin_beta | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
jellyfin_beta | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
jellyfin_beta | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
jellyfin_beta | 10-listen-on-ipv6-by-default.sh: Getting the checksum of /etc/nginx/conf.d/default.conf
jellyfin_beta | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf differs from the packages version
jellyfin_beta | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
jellyfin_beta | /docker-entrypoint.sh: Configuration complete; ready for start up
// nothing on 0.0.0.0:8097
```

Is anyone else successfully running this image?:
* If yes then would you be kind enough to tell me what I'm doing wrong
* If no then perhaps we should fix the image

Hope to hear back

Sincerely

[this]: https://hub.docker.com/layers/jellyfin/jellyfin-vue/unstable/images/sha256-c71ee284328ce721843bb3b275bff96ed7e1b1153a160f1ebb9957ded9093e0e?context=explore

**Comment by crobibero** [comment]
`jellyfin-vue` listens on port `80`, not `8087`.

**Comment by Maxr1998** [comment]
Hi! Jellyfin Vue is only a (future) replacement for the webclient, and doesn't provide the actual media server. So, you'd need `jellyfin/jellyfin:latest` for the server itself. Also, the Vue client uses port 80 (as default for the default nginx webserver), not 8097.

**Comment by ldexterldesign** [comment]
<img width="1904" alt="Screenshot 2020-11-05 at 20 45 12" src="https://user-images.githubusercontent.com/1715809/98294414-d183b000-1fa7-11eb-8a05-a1e4f061f12a.png">

**Comment by ldexterldesign** [comment]
Hope this helps someone else

```yaml
version: "3"
services:

  jellyfin:
    container_name: jellyfin_beta
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    image: jellyfin/jellyfin-vue:unstable
    ports:
      - 8097:80
    restart: unless-stopped
    volumes:
      # - /Volumes/synology/gtd/home/reference:/-data/jellyfin/synology
      - ~/Downloads/-data/-config/jellyfin:/config
      - ~/Downloads/-data:/-data/jellyfin/apple
```

Sincerely
