### ISSUE TITLE
Nginx permission error after setup in image (open() "/run/nginx.pid" failed)

### ISSUE THREAD

**Issue by Friedjof** [jellyfin/jellyfin-vue#2630]
### Description of the bug

After the setup process completes successfully, the container crashes with the following Nginx error:

```
====      Setup finished!        ====

2025/04/29 10:03:13 [notice] 1#1: using the "epoll" event method
2025/04/29 10:03:13 [notice] 1#1: nginx/1.28.0
2025/04/29 10:03:13 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0)
2025/04/29 10:03:13 [notice] 1#1: OS: Linux 4.4.302+
2025/04/29 10:03:13 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2025/04/29 10:03:13 [emerg] 1#1: open() "/run/nginx.pid" failed (13: Permission denied)
nginx: [emerg] open() "/run/nginx.pid" failed (13: Permission denied)
```

**Expected Behavior:**  
After setup completion, Nginx should start normally without permission issues.

**Actual Behavior:**  
The container immediately exits because Nginx cannot write the PID file to `/run/nginx.pid` due to missing permissions.

**Possible Cause:**  
It looks like the `/run` directory is either missing, owned by the wrong user, or not writable by the Nginx process.  
This issue may be specific to how the image handles permissions or the environment setup.

**Proposed Solution:**  
- Create `/run/nginx` with correct permissions during the image build (`RUN mkdir -p /run/nginx && chown nginx:nginx /run/nginx`)  
- Alternatively, configure Nginx to write its PID file to a writable location like `/tmp/nginx.pid` (using `pid /tmp/nginx.pid;` in nginx.conf)

**Environment:**  
- Image Version: [specify if you know it]
- Host System: [e.g., Docker, Ubuntu 24.04 LTS]

### Steps to reproduce

1. Pull the latest version of the image (`docker pull ghcr.io/jellyfin/jellyfin-vue:unstable.2025-04-28.0e15b46`)
2. Start the container using a standard `docker-compose.yml` without custom Nginx configurations.
3. Wait until the setup finishes (you will see `==== Setup finished! ====`)
4. Observe the container logs right after setup.
5. Notice the permission error from Nginx trying to open `/run/nginx.pid`, leading to container crash.

### Expected behavior

After the setup process completes, Nginx should start successfully without any permission errors.  
The container should remain running and serve the application as intended, without crashing due to file system permission issues.

### Logs

```text
====      Setup finished!        ====

2025/04/29 10:03:13 [notice] 1#1: using the "epoll" event method
2025/04/29 10:03:13 [notice] 1#1: nginx/1.28.0
2025/04/29 10:03:13 [notice] 1#1: built by gcc 14.2.0 (Alpine 14.2.0)
2025/04/29 10:03:13 [notice] 1#1: OS: Linux 4.4.302+
2025/04/29 10:03:13 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2025/04/29 10:03:13 [emerg] 1#1: open() "/run/nginx.pid" failed (13: Permission denied)
nginx: [emerg] open() "/run/nginx.pid" failed (13: Permission denied)
```

### Platform

Linux

### Browser

Firefox

### Jellyfin server version

-

### Additional context

```text

```

**Comment by ferferga** [comment]
This has been fixed in this commit:

https://github.com/jellyfin/jellyfin-vue/commit/4e96144e09c83fd98d47208c4d5808ed63da8d2b

Are you sure you have watchtower or any other automatic updating method properly configured?

**Comment by 98jan** [comment]
also for me the newest image tag I can find: unstable.2025-04-28.0e15b46 is failing with this error message ...
Downloaded about 3h ago the new image.

**Comment by ferferga** [comment]
@98jan Can you attach the logs and details of the device where you are running the container? Are you sure you're using that tag? I pulled it and no issues either.

**Comment by 98jan** [comment]
Hi,

I am running it on my Kubernetes Cluster, that are the logs:

`
==== Starting Jellyfin Vue setup ====

Writing data to /usr/share/nginx/html/config.json...
DEFAULT_SERVERS value: jellyfin.home.naj-hosting.de
ALLOW_SERVER_SELECTION value: false
ROUTER_MODE value: history

====      Setup finished!        ====

2025/04/29 20:17:23 [emerg] 1#1: bind() to 0.0.0.0:80 failed (13: Permission denied)
nginx: [emerg] bind() to 0.0.0.0:80 failed (13: Permission denied)
`

That is my deployment.yaml

`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-vue
  template:
    metadata:
      labels:
        app: jellyfin-vue
    spec:
      serviceAccountName: jellyfin
      containers:
        - name: jellyfin-vue
          image: jellyfin/jellyfin-vue:unstable.2025-04-28.0e15b46
          env:
            # Don't allow adding custom servers to vue frontend
            - name: DISABLE_SERVER_SELECTION
              value: "1"
            - name: DEFAULT_SERVERS
              value: jellyfin.${DOMAIN}
          ports:
            - name: http
              containerPort: 80
`

**Comment by ferferga** [comment]
@98jan I'm closing this again since this has nothing to do with the original issue.

The issue is because docker/container runtime is either super outdated (pre-20, if I recall correctly) or doesn't have permission to bind to privileged ports. In `docker run` terms, what you're doing is:

`docker run --rm --network host ghcr.io/jellyfin/jellyfin-vue:unstable` -> docker has no proxy and all the network of the container = to host, so can't open privileged ports.

However, this will work perfectly:

`docker run --rm -p 8080:80 ghcr.io/jellyfin/jellyfin-vue:unstable` -> in host, 8080 is not a privileged port, so it can be mapped succesfully.

My knowledges of kubernetes is a bit oxidated, but, iirc, you must mix `targetPort` somewhere in your schema to match the `docker run` behaviour. Additionally, [this is a good resource](https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports) regardless

**Comment by 98jan** [comment]
Hi @ferferga,

you are right the binding of port 80 is the problem, because that is a privileged port.

Just fixed it now with overwriting the start parameter to update the nginx.conf to start by default on 8080:

```YAML
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin-vue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin-vue
  template:
    metadata:
      labels:
        app: jellyfin-vue
    spec:
      serviceAccountName: jellyfin
      containers:
        - name: jellyfin-vue
          image: jellyfin/jellyfin-vue:unstable.2025-04-28.0e15b46
          env:
            # Don't allow adding custom servers to vue frontend
            - name: DISABLE_SERVER_SELECTION
              value: "1"
            - name: DEFAULT_SERVERS
              value: jellyfin.${DOMAIN}
          ports:
            - name: http
              containerPort: 8080
          command: ["/bin/sh", "-c"]
          args:
            - sed -i 's/listen 80;/listen 8080;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
 ```
